# Generated by Django 4.2.8 on 2024-01-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanagement', '0002_remove_userdetails_designation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='designation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
