# Generated by Django 4.2.8 on 2024-01-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanagement', '0004_leavetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='user_details',
        ),
    ]
