# Generated by Django 4.2.8 on 2024-01-16 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leavemanagement', '0005_remove_leavetype_user_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('leavedays', models.IntegerField()),
                ('reason', models.TextField()),
                ('leavetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leavemanagement.leavetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
