# Generated by Django 4.2.8 on 2024-01-16 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanagement', '0008_alter_lms_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lms',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leavemanagement.leavetype'),
        ),
    ]
