# Generated by Django 5.0.1 on 2024-01-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanagement', '0010_remove_userdetails_designation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lms',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='lms',
            name='startdate',
        ),
        migrations.AddField(
            model_name='lms',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lms',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
